/**
 * Local MITRE ATT&CK Mapping Dataset
 * No external API calls required.
 */
const MitreData = {
    "T1059.001": { tactic: "Execution", technique: "Command and Scripting Interpreter: PowerShell" },
    "T1059.003": { tactic: "Execution", technique: "Command and Scripting Interpreter: Windows Command Shell" },
    "T1059.005": { tactic: "Execution", technique: "Command and Scripting Interpreter: Visual Basic" },
    "T1105": { tactic: "Command and Control", technique: "Ingress Tool Transfer" },
    "T1027": { tactic: "Defense Evasion", technique: "Obfuscated Files or Information" },
    "T1027.002": { tactic: "Defense Evasion", technique: "Obfuscated Files or Information: Software Packing" },
    "T1053.005": { tactic: "Persistence", technique: "Scheduled Task/Job: Scheduled Task" },
    "T1547.001": { tactic: "Persistence", technique: "Boot or Logon Autostart Execution: Registry Run Keys / Startup Folder" },
    "T1546.003": { tactic: "Persistence", technique: "Event-Triggered Execution: Windows Management Instrumentation Event Subscription" },
    "T1546.013": { tactic: "Persistence", technique: "Event-Triggered Execution: PowerShell Profile" },
    "T1543.003": { tactic: "Persistence", technique: "Create or Modify System Process: Windows Service" },
    "T1562.001": { tactic: "Defense Evasion", technique: "Impair Defenses: Disable or Modify Tools" },
    "T1562.002": { tactic: "Defense Evasion", technique: "Impair Defenses: Disable Windows Event Logging" },
    "T1562.006": { tactic: "Defense Evasion", technique: "Impair Defenses: Indicator Blocking" },
    "T1003.001": { tactic: "Credential Access", technique: "OS Credential Dumping: LSASS Memory" },
    "T1003.002": { tactic: "Credential Access", technique: "OS Credential Dumping: Security Account Manager" },
    "T1555": { tactic: "Credential Access", technique: "Credentials from Password Stores" },
    "T1555.001": { tactic: "Credential Access", technique: "Credentials from Password Stores: Keychain" },
    "T1056.001": { tactic: "Collection", technique: "Input Capture: Keylogging" },
    "T1134": { tactic: "Defense Evasion", technique: "Access Token Manipulation" },
    "T1047": { tactic: "Execution", technique: "Windows Management Instrumentation" },
    "T1021.006": { tactic: "Lateral Movement", technique: "Remote Services: Windows Remote Management" },
    "T1021.002": { tactic: "Lateral Movement", technique: "Remote Services: SMB/Windows Admin Shares" },
    "T1021.001": { tactic: "Lateral Movement", technique: "Remote Services: Remote Desktop Protocol" },
    "T1021.004": { tactic: "Lateral Movement", technique: "Remote Services: SSH" },
    "T1055": { tactic: "Defense Evasion", technique: "Process Injection" },
    "T1055.001": { tactic: "Defense Evasion", technique: "Process Injection: Dynamic-link Library Injection" },
    "T1055.003": { tactic: "Defense Evasion", technique: "Process Injection: Thread Execution Hijacking" },
    "T1055.004": { tactic: "Defense Evasion", technique: "Process Injection: Asynchronous Procedure Call" },
    "T1490": { tactic: "Impact", technique: "Inhibit System Recovery" },
    "T1486": { tactic: "Impact", technique: "Data Encrypted for Impact" },
    "T1485": { tactic: "Impact", technique: "Data Destruction" },
    "T1489": { tactic: "Impact", technique: "Service Stop" },
    "T1070.001": { tactic: "Defense Evasion", technique: "Indicator Removal: Clear Windows Event Logs" },
    "T1087.001": { tactic: "Discovery", technique: "Account Discovery: Local Account" },
    "T1087.002": { tactic: "Discovery", technique: "Account Discovery: Domain Account" },
    "T1018": { tactic: "Discovery", technique: "Remote System Discovery" },
    "T1016": { tactic: "Discovery", technique: "System Network Configuration Discovery" },
    "T1049": { tactic: "Discovery", technique: "System Network Connections Discovery" },
    "T1057": { tactic: "Discovery", technique: "Process Discovery" },
    "T1007": { tactic: "Discovery", technique: "System Service Discovery" },
    "T1082": { tactic: "Discovery", technique: "System Information Discovery" },
    "T1033": { tactic: "Discovery", technique: "System Owner/User Discovery" },
    "T1069.001": { tactic: "Discovery", technique: "Permission Groups Discovery: Local Groups" },
    "T1482": { tactic: "Discovery", technique: "Domain Trust Discovery" },
    "T1083": { tactic: "Discovery", technique: "File and Directory Discovery" },
    "T1213": { tactic: "Collection", technique: "Data from Information Repositories" },
    "T1115": { tactic: "Collection", technique: "Clipboard Data" },
    "T1113": { tactic: "Collection", technique: "Screen Capture" },
    "T1123": { tactic: "Collection", technique: "Audio Capture" },
    "T1125": { tactic: "Collection", technique: "Video Capture" },
    "T1048.001": { tactic: "Exfiltration", technique: "Exfiltration Over Alternative Protocol: Exfiltration Over Symmetric Encrypted Non-C2 Protocol" },
    "T1048.002": { tactic: "Exfiltration", technique: "Exfiltration Over Alternative Protocol: Exfiltration Over Asymmetric Encrypted Non-C2 Protocol" },
    "T1048.003": { tactic: "Exfiltration", technique: "Exfiltration Over Alternative Protocol: Exfiltration Over Unencrypted Non-C2 Protocol" },
    "T1567": { tactic: "Exfiltration", technique: "Exfiltration Over Web Service" },
    "T1552.001": { tactic: "Credential Access", technique: "Unsecured Credentials: Credentials In Files" },
    "T1552.004": { tactic: "Credential Access", technique: "Unsecured Credentials: Private Keys" },
    "T1552.005": { tactic: "Credential Access", technique: "Unsecured Credentials: Cloud Instance Metadata API" },
    "T1548.002": { tactic: "Privilege Escalation", technique: "Abuse Elevation Control Mechanism: Bypass User Account Control" },
    "T1068": { tactic: "Privilege Escalation", technique: "Exploitation for Privilege Escalation" },
    "T1574.001": { tactic: "Privilege Escalation", technique: "Hijack Execution Flow: DLL Search Order Hijacking" },
    "T1574.009": { tactic: "Privilege Escalation", technique: "Hijack Execution Flow: Path Interception by Unquoted Path" },
    "T1218.005": { tactic: "Defense Evasion", technique: "System Binary Proxy Execution: MSHTA" },
    "T1218.011": { tactic: "Defense Evasion", technique: "System Binary Proxy Execution: Rundll32" },
    "T1218.010": { tactic: "Defense Evasion", technique: "System Binary Proxy Execution: Regsvr32" },
    "T1218.004": { tactic: "Defense Evasion", technique: "System Binary Proxy Execution: InstallUtil" },
    "T1218.007": { tactic: "Defense Evasion", technique: "System Binary Proxy Execution: Msiexec" },
    "T1197": { tactic: "Defense Evasion", technique: "BITS Jobs" },
    "T1550.002": { tactic: "Defense Evasion", technique: "Use Alternate Authentication Material: Pass the Hash" },
    "T1556.001": { tactic: "Credential Access", technique: "Modify Authentication Process: Domain Controller Authentication" },
    "T1484": { tactic: "Defense Evasion", technique: "Domain Policy Modification" },
    "T1037": { tactic: "Persistence", technique: "Boot or Logon Initialization Scripts" },
    "T1546.012": { tactic: "Persistence", technique: "Event-Triggered Execution: Image File Execution Options Injection" },
    "T1546.015": { tactic: "Persistence", technique: "Event-Triggered Execution: Component Object Model Hijacking" },
    "T1546.001": { tactic: "Persistence", technique: "Event-Triggered Execution: Change Default File Association" },
    "T1547.003": { tactic: "Persistence", technique: "Boot or Logon Autostart Execution: Time Providers" },
    "T1547.004": { tactic: "Persistence", technique: "Boot or Logon Autostart Execution: Winlogon Helper DLL" },
    "T1548.002": { tactic: "Privilege Escalation", technique: "Abuse Elevation Control Mechanism: Bypass User Account Control" },
    "T1560.001": { tactic: "Collection", technique: "Archive Collected Data: Archive via Utility" },
    "T1564.003": { tactic: "Defense Evasion", technique: "Hide Artifacts: Hidden Window" },
    "T1090": { tactic: "Command and Control", technique: "Proxy" },
    "T1071.001": { tactic: "Command and Control", technique: "Application Layer Protocol: Web Protocols" },
    "T1071.004": { tactic: "Command and Control", technique: "Application Layer Protocol: DNS" },
    "T1518.001": { tactic: "Discovery", technique: "Software Discovery: Security Software Discovery" }
};

const MitreEngine = {
    getTechniqueInfo: (id) => {
        return MitreData[id] || { tactic: "Unknown", technique: "Unknown Technique" };
    }
};