/**
 * Detection Signatures for PowerShell Security Analyzer
 * Contains 250+ meaningful, categorized static analysis rules.
 * Format: {id, n: name, c: category, s: severity, p: pattern (regex), d: description, r: recommendation, m: mitre[]}
 */
const Signatures = [
// --- EXECUTION (1-25) ---
{id:"PSA-001",n:"Invoke-Expression",c:"Execution",s:"High",p:"\\b(Invoke-Expression|iex)\\b",d:"Dynamic expression execution detected.",r:"Review dynamically executed content for malicious payloads.",m:["T1059.001"]},
{id:"PSA-002",n:"Invoke-Command",c:"Execution",s:"Medium",p:"\\b(Invoke-Command|icm)\\b",d:"Remote or local command invocation.",r:"Verify the target and command being executed.",m:["T1059.001"]},
{id:"PSA-003",n:"Start-Process",c:"Execution",s:"Medium",p:"\\bStart-Process\\b",d:"Spawns a new process.",r:"Check the executable path and arguments.",m:["T1059.001"]},
{id:"PSA-004",n:"Start-Job",c:"Execution",s:"Low",p:"\\bStart-Job\\b",d:"Asynchronous background job creation.",r:"Ensure background jobs are expected.",m:["T1059.001"]},
{id:"PSA-005",n:"Start-ThreadJob",c:"Execution",s:"Low",p:"\\bStart-ThreadJob\\b",d:"Lightweight background job creation.",r:"Verify job purpose.",m:["T1059.001"]},
{id:"PSA-006",n:"PowerShell.exe Invocation",c:"Execution",s:"Medium",p:"\\bpowershell\\.exe\\b",d:"Explicit PowerShell executable call.",r:"Check command-line arguments for obfuscation.",m:["T1059.001"]},
{id:"PSA-007",n:"Pwsh.exe Invocation",c:"Execution",s:"Medium",p:"\\bpwsh\\.exe\\b",d:"PowerShell Core executable call.",r:"Check command-line arguments.",m:["T1059.001"]},
{id:"PSA-008",n:"CMD.exe Invocation",c:"Execution",s:"Medium",p:"\\bcmd\\.exe\\b",d:"Legacy command processor invocation.",r:"Investigate why CMD is being called from PowerShell.",m:["T1059.003"]},
{id:"PSA-009",n:"WScript Invocation",c:"Execution",s:"High",p:"\\bwscript\\.exe\\b",d:"Windows script host execution.",r:"Commonly used for VBScript/JS malware.",m:["T1059.005"]},
{id:"PSA-010",n:"CScript Invocation",c:"Execution",s:"High",p:"\\bcscript\\.exe\\b",d:"Console script host execution.",r:"Investigate script arguments.",m:["T1059.005"]},
{id:"PSA-011",n:"MSHTA Execution",c:"Execution",s:"Critical",p:"\\bmshta\\.exe\\b",d:"HTML Application host execution.",r:"Frequently abused for payload delivery.",m:["T1218.005"]},
{id:"PSA-012",n:"Rundll32 Execution",c:"Execution",s:"High",p:"\\brundll32\\.exe\\b",d:"Execute code via DLL.",r:"Verify DLL path and export function.",m:["T1218.011"]},
{id:"PSA-013",n:"Regsvr32 Execution",c:"Execution",s:"High",p:"\\bregsvr32\\.exe\\b",d:"Register and execute DLL/COM objects.",r:"Check for squiblydoo or similar bypasses.",m:["T1218.010"]},
{id:"PSA-014",n:"Certutil Execution",c:"Execution",s:"High",p:"\\bcertutil\\.exe\\b",d:"Certificate utility abused for file download/encoding.",r:"Check for -urlcache or -decode flags.",m:["T1105"]},
{id:"PSA-015",n:"Bitsadmin Execution",c:"Execution",s:"High",p:"\\bbitsadmin\\.exe\\b",d:"Background Intelligent Transfer Service abuse.",r:"Check for /transfer flags indicating download.",m:["T1105"]},
{id:"PSA-016",n:"WMIC Execution",c:"Execution",s:"High",p:"\\bwmic\\.exe\\b",d:"WMI command-line utility execution.",r:"Often used for discovery or lateral movement.",m:["T1047"]},
{id:"PSA-017",n:"Msiexec Execution",c:"Execution",s:"High",p:"\\bmsiexec\\.exe\\b",d:"Windows installer execution.",r:"Check for /i or /qn flags with remote URLs.",m:["T1218.007"]},
{id:"PSA-018",n:"InstallUtil Execution",c:"Execution",s:"High",p:"\\binstallutil\\.exe\\b",d:"Installer tool abused for execution.",r:"Check for /logfile= or /LogToConsole=false.",m:["T1218.004"]},
{id:"PSA-019",n:"Schtasks Execution",c:"Execution",s:"High",p:"\\bschtasks\\.exe\\b",d:"Scheduled task manipulation.",r:"Verify task creation or modification.",m:["T1053.005"]},
{id:"PSA-020",n:"SC.exe Execution",c:"Execution",s:"Medium",p:"\\bsc\\.exe\\b",d:"Service control manager interaction.",r:"Check for service creation or modification.",m:["T1543.003"]},
{id:"PSA-021",n:"Invoke-Item",c:"Execution",s:"Low",p:"\\bInvoke-Item\\b",d:"Opens a file or directory.",r:"Ensure the target path is safe.",m:["T1059.001"]},
{id:"PSA-022",n:"Invoke-Expression Alias",c:"Execution",s:"High",p:"\\b&\\s*\\(",d:"Call operator used for dynamic execution.",r:"Review the evaluated string.",m:["T1059.001"]},
{id:"PSA-023",n:"Invoke-Command via WinRM",c:"Execution",s:"High",p:"\\bInvoke-Command\\s+.*-ComputerName\\b",d:"Remote execution via WinRM.",r:"Verify remote host and intent.",m:["T1021.006"]},
{id:"PSA-024",n:"WMI Process Creation",c:"Execution",s:"High",p:"\\bWin32_Process\\b.*\\bCreate\\b",d:"WMI process creation.",r:"Investigate the command line being executed.",m:["T1047"]},
{id:"PSA-025",n:"COM Object Execution",c:"Execution",s:"Medium",p:"\\bNew-Object\\s+-ComObject\\b",d:"COM object instantiation.",r:"Check for WScript.Shell or similar objects.",m:["T1059.001"]},

// --- NETWORK / DOWNLOAD (26-50) ---
{id:"PSA-026",n:"Invoke-WebRequest",c:"Network",s:"Medium",p:"\\b(Invoke-WebRequest|iwr|curl)\\b",d:"HTTP/HTTPS request initiated.",r:"Review the target URI and downloaded content.",m:["T1105"]},
{id:"PSA-027",n:"Invoke-RestMethod",c:"Network",s:"Medium",p:"\\b(Invoke-RestMethod|irm)\\b",d:"REST API interaction.",r:"Verify the endpoint and data being sent/received.",m:["T1105"]},
{id:"PSA-028",n:"WebClient DownloadString",c:"Network",s:"High",p:"\\bWebClient\\b.*\\bDownloadString\\b",d:"String download via WebClient.",r:"Commonly used to fetch and execute remote scripts.",m:["T1105"]},
{id:"PSA-029",n:"WebClient DownloadFile",c:"Network",s:"High",p:"\\bWebClient\\b.*\\bDownloadFile\\b",d:"File download via WebClient.",r:"Check the destination file path.",m:["T1105"]},
{id:"PSA-030",n:"HTTP Protocol",c:"Network",s:"Low",p:"\\bhttp://",d:"Plaintext HTTP URL detected.",r:"Prefer HTTPS. Verify the destination.",m:["T1071.001"]},
{id:"PSA-031",n:"HTTPS Protocol",c:"Network",s:"Low",p:"\\bhttps://",d:"Encrypted HTTP URL detected.",r:"Verify the destination domain.",m:["T1071.001"]},
{id:"PSA-032",n:"TCP Client",c:"Network",s:"High",p:"\\bTcpClient\\b",d:"Raw TCP socket creation.",r:"Investigate the target IP and port.",m:["T1071.001"]},
{id:"PSA-033",n:"UDP Client",c:"Network",s:"High",p:"\\bUdpClient\\b",d:"Raw UDP socket creation.",r:"Investigate the target IP and port.",m:["T1071.001"]},
{id:"PSA-034",n:"Socket Creation",c:"Network",s:"High",p:"\\bNet\\.Sockets\\.Socket\\b",d:"Low-level socket creation.",r:"Highly suspicious in standard scripts.",m:["T1071.001"]},
{id:"PSA-035",n:"DNS Resolution",c:"Network",s:"Low",p:"\\bResolve-DnsName\\b",d:"DNS query performed.",r:"Check for DNS tunneling or C2 beacons.",m:["T1071.004"]},
{id:"PSA-036",n:"Test-NetConnection",c:"Network",s:"Low",p:"\\bTest-NetConnection\\b",d:"Network connectivity check.",r:"Verify the target host and port.",m:["T1046"]},
{id:"PSA-037",n:"FTP Protocol",c:"Network",s:"High",p:"\\bftp://",d:"FTP URL detected.",r:"FTP is unencrypted and often abused.",m:["T1048.002"]},
{id:"PSA-038",n:"SMB/UNC Path",c:"Network",s:"Medium",p:"\\\\\\\\[\\w.-]+",d:"UNC path access detected.",r:"Check for lateral movement or credential harvesting.",m:["T1021.002"]},
{id:"PSA-039",n:"Net.WebRequest",c:"Network",s:"Medium",p:"\\bNet\\.WebRequest\\b",d:"Low-level web request creation.",r:"Review the URI and method.",m:["T1105"]},
{id:"PSA-040",n:"Port Scan Indicator",c:"Network",s:"Medium",p:"\\bTest-NetConnection.*-Port\\b",d:"Port scanning activity.",r:"Investigate the target and port range.",m:["T1046"]},
{id:"PSA-041",n:"Proxy Bypass",c:"Network",s:"Medium",p:"\\b-ProxyUseDefaultCredentials\\b.*\\b-Proxy\\b",d:"Proxy configuration manipulation.",r:"Check if traffic is being routed suspiciously.",m:["T1090"]},
{id:"PSA-042",n:"WinHTTP COM",c:"Network",s:"High",p:"\\bWinHttp\\.WinHttpRequest\\b",d:"WinHTTP COM object usage.",r:"Often used to bypass network controls.",m:["T1105"]},
{id:"PSA-043",n:"XML HTTP Request",c:"Network",s:"Medium",p:"\\bMSXML2\\.XMLHTTP\\b",d:"Legacy XML HTTP request.",r:"Check the destination URL.",m:["T1105"]},
{id:"PSA-044",n:"Ping Sweep",c:"Network",s:"Low",p:"\\bTest-Connection\\b",d:"ICMP echo request.",r:"Could indicate network discovery.",m:["T1046"]},
{id:"PSA-045",n:"Netstat Execution",c:"Network",s:"Low",p:"\\bnetstat\\b",d:"Network statistics display.",r:"Check for discovery intent.",m:["T1049"]},
{id:"PSA-046",n:"Arp Execution",c:"Network",s:"Low",p:"\\barp\\b",d:"ARP cache display.",r:"Network discovery indicator.",m:["T1016"]},
{id:"PSA-047",n:"Route Print",c:"Network",s:"Low",p:"\\broute\\s+print\\b",d:"Routing table display.",r:"Network discovery indicator.",m:["T1016"]},
{id:"PSA-048",n:"IPConfig Execution",c:"Network",s:"Low",p:"\\bipconfig\\b",d:"IP configuration display.",r:"System discovery indicator.",m:["T1016"]},
{id:"PSA-049",n:"External IP Check",c:"Network",s:"Low",p:"\\bapi\\.ipify\\.org|checkip\\.amazonaws\\.com",d:"External IP address retrieval.",r:"Common in C2 beacons.",m:["T1016"]},
{id:"PSA-050",n:"Raw HTTP Request",c:"Network",s:"High",p:"\\bGET\\s+/|POST\\s+/",d:"Raw HTTP method strings.",r:"May indicate custom C2 protocol.",m:["T1071.001"]},

// --- ENCODING / OBFUSCATION (51-100) ---
{id:"PSA-051",n:"EncodedCommand Flag",c:"Obfuscation",s:"Critical",p:"\\b(-EncodedCommand|-e|\\s+-enc)\\b",d:"Base64 encoded command execution.",r:"Decode and analyze the payload immediately.",m:["T1027"]},
{id:"PSA-052",n:"FromBase64String",c:"Obfuscation",s:"High",p:"\\bFromBase64String\\b",d:"Base64 decoding operation.",r:"Identify what is being decoded.",m:["T1027"]},
{id:"PSA-053",n:"ToBase64String",c:"Obfuscation",s:"Medium",p:"\\bToBase64String\\b",d:"Base64 encoding operation.",r:"May indicate data exfiltration preparation.",m:["T1027"]},
{id:"PSA-054",n:"Char Array Conversion",c:"Obfuscation",s:"Medium",p:"\\[char\\]\\[",d:"Character array reconstruction.",r:"Common obfuscation technique.",m:["T1027"]},
{id:"PSA-055",n:"Hexadecimal String",c:"Obfuscation",s:"Medium",p:"0x[0-9a-fA-F]{2,}",d:"Hexadecimal literal detected.",r:"Check if used for string obfuscation.",m:["T1027"]},
{id:"PSA-056",n:"String Replace Chain",c:"Obfuscation",s:"Medium",p:"\\.Replace\\(.*\\)\\.Replace\\(",d:"Multiple string replacements.",r:"Often used to deobfuscate commands.",m:["T1027"]},
{id:"PSA-057",n:"Join Operator",c:"Obfuscation",s:"Low",p:"\\b-join\\b",d:"Array joining operation.",r:"Check if used to reconstruct obfuscated strings.",m:["T1027"]},
{id:"PSA-058",n:"Format Operator",c:"Obfuscation",s:"Low",p:"\\b-f\\b",d:"String formatting operator.",r:"Can be used for dynamic string building.",m:["T1027"]},
{id:"PSA-059",n:"Backtick Abuse",c:"Obfuscation",s:"Medium",p:"`{2,}",d:"Excessive use of escape characters.",r:"Used to break signature matching.",m:["T1027"]},
{id:"PSA-060",n:"Concatenation",c:"Obfuscation",s:"Low",p:"\\+\\s*['\"]",d:"String concatenation.",r:"Check for command fragmentation.",m:["T1027"]},
{id:"PSA-061",n:"Subexpression Operator",c:"Obfuscation",s:"Low",p:"\\$\\(",d:"Subexpression evaluation.",r:"Can be used to dynamically resolve commands.",m:["T1027"]},
{id:"PSA-062",n:"Invoke-Expression via Variable",c:"Obfuscation",s:"High",p:"\\&\\s*\\$[\\w]+",d:"Dynamic invocation via variable.",r:"Trace the variable assignment.",m:["T1027"]},
{id:"PSA-063",n:"XOR Obfuscation",c:"Obfuscation",s:"High",p:"\\bxor\\b",d:"XOR operation detected.",r:"Commonly used to hide payloads.",m:["T1027"]},
{id:"PSA-064",n:"RC4 Implementation",c:"Obfuscation",s:"Critical",p:"\\bRC4\\b|\\bRijndael\\b",d:"Encryption algorithm detected.",r:"Indicates hidden payload or C2 traffic.",m:["T1027"]},
{id:"PSA-065",n:"AES Encryption",c:"Obfuscation",s:"Medium",p:"\\bAES\\b",d:"AES encryption detected.",r:"Verify if legitimate or malicious.",m:["T1027"]},
{id:"PSA-066",n:"GZIP Compression",c:"Obfuscation",s:"Medium",p:"\\bGZipStream\\b",d:"Data compression detected.",r:"Often used to shrink encoded payloads.",m:["T1027"]},
{id:"PSA-067",n:"Random Variable Names",c:"Obfuscation",s:"Low",p:"\\$[a-zA-Z0-9]{16,}",d:"Unusually long variable names.",r:"May indicate automated obfuscation.",m:["T1027"]},
{id:"PSA-068",n:"Mixed Case Cmdlet",c:"Obfuscation",s:"Low",p:"\\b[iI][nN][vV][oO][kK][eE]-[eE][xX][pP][rR][eE][sS][sS][iI][oO][nN]\\b",d:"Irregular casing in cmdlet.",r:"Attempt to evade case-sensitive signatures.",m:["T1027"]},
{id:"PSA-069",n:"Nested Brackets",c:"Obfuscation",s:"Medium",p:"\\[\\[.*\\]\\]",d:"Deeply nested arrays or expressions.",r:"Obfuscation technique.",m:["T1027"]},
{id:"PSA-070",n:"String Splitting",c:"Obfuscation",s:"Medium",p:"\\'\\s*,\\s*\\'",d:"String split by character.",r:"Used to reconstruct keywords.",m:["T1027"]},
{id:"PSA-071",n:"Unicode Escape",c:"Obfuscation",s:"Medium",p:"\\\\u[0-9a-fA-F]{4}",d:"Unicode escape sequence.",r:"Can hide malicious strings.",m:["T1027"]},
{id:"PSA-072",n:"Whitespace Stuffing",c:"Obfuscation",s:"Low",p:"\\s{5,}",d:"Excessive whitespace.",r:"Used to break line-based analyzers.",m:["T1027"]},
{id:"PSA-073",n:"Comment Stuffing",c:"Obfuscation",s:"Low",p:"#[\\s\\S]{50,}#",d:"Large comment blocks.",r:"May hide data or break parsers.",m:["T1027"]},
{id:"PSA-074",n:"Splatting Abuse",c:"Obfuscation",s:"Medium",p:"\\@[\\w]+",d:"Splatting operator usage.",r:"Can be used to obscure parameters.",m:["T1027"]},
{id:"PSA-075",n:"Alias Abuse",c:"Obfuscation",s:"Low",p:"\\b(iex|icm|iwr|irm|gps|gsv)\\b",d:"Use of PowerShell aliases.",r:"Resolve aliases to full cmdlet names.",m:["T1027"]},
{id:"PSA-076",n:"Base64 Blob",c:"Obfuscation",s:"High",p:"[A-Za-z0-9+/]{50,}={0,2}",d:"Long Base64-like string.",r:"Extract and decode for analysis.",m:["T1027"]},
{id:"PSA-077",n:"Octal Representation",c:"Obfuscation",s:"Medium",p:"\\\\[0-7]{3}",d:"Octal character representation.",r:"String obfuscation technique.",m:["T1027"]},
{id:"PSA-078",n:"Binary Representation",c:"Obfuscation",s:"Medium",p:"\\\\b[01]{8}",d:"Binary character representation.",r:"String obfuscation technique.",m:["T1027"]},
{id:"PSA-079",n:"Regex Obfuscation",c:"Obfuscation",s:"Medium",p:"\\[regex\\]::",d:"Direct regex class usage.",r:"Can be used for dynamic string manipulation.",m:["T1027"]},
{id:"PSA-080",n:"Reflection Usage",c:"Obfuscation",s:"High",p:"\\bReflection\\b",d:".NET Reflection usage.",r:"Often used for memory loading or AMSI bypass.",m:["T1027"]},

// --- AMSI / SECURITY BYPASS (81-110) ---
{id:"PSA-081",n:"AMSI Bypass Indicator",c:"Defense Evasion",s:"Critical",p:"\\bamsiInitFailed\\b|\\bAmsiScanBuffer\\b",d:"Known AMSI bypass pattern.",r:"Block execution and investigate.",m:["T1562.001"]},
{id:"PSA-082",n:"Memory Patching",c:"Defense Evasion",s:"Critical",p:"\\bVirtualProtect\\b|\\bWriteProcessMemory\\b",d:"Memory protection modification.",r:"Strong indicator of in-memory evasion.",m:["T1562.001"]},
{id:"PSA-083",n:"Execution Policy Bypass",c:"Defense Evasion",s:"High",p:"\\b-ExecutionPolicy\\s+(Bypass|Unrestricted)\\b",d:"Execution policy override.",r:"Verify if this is expected administrative behavior.",m:["T1562.001"]},
{id:"PSA-084",n:"Constrained Language Mode Bypass",c:"Defense Evasion",s:"Critical",p:"\\b__PSLockDownPolicy\\b",d:"Attempt to manipulate CLM.",r:"Investigate the execution context.",m:["T1562.001"]},
{id:"PSA-085",n:"Set-ExecutionPolicy",c:"Defense Evasion",s:"Medium",p:"\\bSet-ExecutionPolicy\\b",d:"Changing system execution policy.",r:"Review the target scope and policy value.",m:["T1562.001"]},
{id:"PSA-086",n:"AppLocker Bypass",c:"Defense Evasion",s:"High",p:"\\bAppLocker\\b",d:"AppLocker reference.",r:"Check for bypass techniques.",m:["T1562.001"]},
{id:"PSA-087",n:"Device Guard Bypass",c:"Defense Evasion",s:"High",p:"\\bDeviceGuard\\b",d:"Device Guard reference.",r:"Check for bypass techniques.",m:["T1562.001"]},
{id:"PSA-088",n:"Script Block Logging Disable",c:"Defense Evasion",s:"High",p:"\\bScriptBlockLogging\\b.*\\b0\\b",d:"Attempt to disable logging.",r:"Highly suspicious behavior.",m:["T1562.002"]},
{id:"PSA-089",n:"Transcription Disable",c:"Defense Evasion",s:"High",p:"\\bEnableTranscription\\b.*\\b0\\b",d:"Attempt to disable transcription.",r:"Highly suspicious behavior.",m:["T1562.002"]},
{id:"PSA-090",n:"ETW Patching",c:"Defense Evasion",s:"Critical",p:"\\bEtwEventWrite\\b|\\bpatchETW\\b",d:"Event Tracing for Windows manipulation.",r:"Strong indicator of advanced evasion.",m:["T1562.006"]},
{id:"PSA-091",n:"Ntdll Unhooking",c:"Defense Evasion",s:"Critical",p:"\\bntdll\\.dll\\b.*\\bunhook\\b",d:"API unhooking attempt.",r:"Advanced evasion technique.",m:["T1562.001"]},
{id:"PSA-092",n:"Assembly Load",c:"Defense Evasion",s:"High",p:"\\bAssembly\\]::Load\\b",d:"In-memory assembly loading.",r:"Check for reflective DLL loading.",m:["T1027.002"]},
{id:"PSA-093",n:"Defender Exclusion Add",c:"Defense Evasion",s:"Critical",p:"\\bAdd-MpPreference\\b",d:"Windows Defender exclusion modification.",r:"Investigate the excluded path or process.",m:["T1562.001"]},
{id:"PSA-094",n:"Realtime Monitoring Disable",c:"Defense Evasion",s:"Critical",p:"\\bDisableRealtimeMonitoring\\b",d:"Defender realtime protection disabled.",r:"Critical security degradation.",m:["T1562.001"]},
{id:"PSA-095",n:"Tamper Protection Disable",c:"Defense Evasion",s:"Critical",p:"\\bTamperProtection\\b",d:"Defender tamper protection targeted.",r:"Critical security degradation.",m:["T1562.001"]},
{id:"PSA-096",n:"Clear Event Log",c:"Defense Evasion",s:"High",p:"\\bClear-EventLog\\b|\\bwevtutil\\s+cl\\b",d:"Event log clearing.",r:"Anti-forensics behavior.",m:["T1070.001"]},
{id:"PSA-097",n:"Process Masquerading",c:"Defense Evasion",s:"High",p:"\\b-WindowStyle\\s+Hidden\\b",d:"Hidden window execution.",r:"Attempt to hide activity from user.",m:["T1564.003"]},
{id:"PSA-098",n:"Bypass Flag",c:"Defense Evasion",s:"Medium",p:"\\b-bypass\\b",d:"Generic bypass flag.",r:"Review the context of the bypass.",m:["T1562.001"]},
{id:"PSA-099",n:"Unrestricted Flag",c:"Defense Evasion",s:"Medium",p:"\\b-unrestricted\\b",d:"Unrestricted execution flag.",r:"Review the context.",m:["T1562.001"]},
{id:"PSA-100",n:"NoProfile Flag",c:"Defense Evasion",s:"Low",p:"\\b-NoProfile\\b",d:"Profile loading disabled.",r:"Common in both legitimate and malicious scripts.",m:["T1562.001"]},

// --- CREDENTIAL ACCESS (101-125) ---
{id:"PSA-101",n:"LSASS Reference",c:"Credential Access",s:"Critical",p:"\\blsass\\.exe\\b",d:"Local Security Authority Subsystem Service targeted.",r:"Strong indicator of credential dumping.",m:["T1003.001"]},
{id:"PSA-102",n:"Procdump Reference",c:"Credential Access",s:"Critical",p:"\\bprocdump\\b",d:"Sysinternals Procdump utility.",r:"Often used to dump LSASS memory.",m:["T1003.001"]},
{id:"PSA-103",n:"Mimikatz Reference",c:"Credential Access",s:"Critical",p:"\\bmimikatz\\b",d:"Mimikatz tool reference.",r:"Definitive credential theft indicator.",m:["T1003.001"]},
{id:"PSA-104",n:"Get-Credential",c:"Credential Access",s:"Medium",p:"\\bGet-Credential\\b",d:"Credential prompt invocation.",r:"Verify if this is expected user interaction.",m:["T1056.001"]},
{id:"PSA-105",n:"Credential Manager",c:"Credential Access",s:"High",p:"\\bCredentialManager\\b|\\bVaultCmd\\b",d:"Windows Credential Manager access.",r:"Check for credential harvesting.",m:["T1555"]},
{id:"PSA-106",n:"SAM Hive Access",c:"Credential Access",s:"Critical",p:"\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\SecurityProviders\\\\SAM",d:"SAM registry hive targeted.",r:"Credential dumping indicator.",m:["T1003.002"]},
{id:"PSA-107",n:"Security Hive Access",c:"Credential Access",s:"Critical",p:"\\\\SECURITY\\b",d:"SECURITY registry hive targeted.",r:"Credential dumping indicator.",m:["T1003.002"]},
{id:"PSA-108",n:"DPAPI Reference",c:"Credential Access",s:"High",p:"\\bDPAPI\\b",d:"Data Protection API reference.",r:"May indicate browser or credential decryption.",m:["T1555"]},
{id:"PSA-109",n:"Token Manipulation",c:"Credential Access",s:"High",p:"\\bImpersonateLoggedOnUser\\b|\\bDuplicateToken\\b",d:"Token manipulation API.",r:"Privilege escalation or lateral movement.",m:["T1134"]},
{id:"PSA-110",n:"Net User Command",c:"Credential Access",s:"Medium",p:"\\bnet\\s+user\\b",d:"Local user account management.",r:"Check for account creation or password changes.",m:["T1087.001"]},
{id:"PSA-111",n:"Net Localgroup",c:"Credential Access",s:"Medium",p:"\\bnet\\s+localgroup\\b",d:"Local group management.",r:"Check for addition to Administrators group.",m:["T1078"]},
{id:"PSA-112",n:"Whoami Execution",c:"Discovery",s:"Low",p:"\\bwhoami\\b",d:"Current user context discovery.",r:"Common in both admin and attacker workflows.",m:["T1033"]},
{id:"PSA-113",n:"Systeminfo Execution",c:"Discovery",s:"Low",p:"\\bsysteminfo\\b",d:"System information gathering.",r:"Reconnaissance indicator.",m:["T1082"]},
{id:"PSA-114",n:"Hostname Execution",c:"Discovery",s:"Low",p:"\\bhostname\\b",d:"Hostname discovery.",r:"Reconnaissance indicator.",m:["T1082"]},
{id:"PSA-115",n:"Sekurlsa Reference",c:"Credential Access",s:"Critical",p:"\\bsekurlsa\\b",d:"Mimikatz sekurlsa module.",r:"Definitive credential theft indicator.",m:["T1003.001"]},
{id:"PSA-116",n:"Password Harvesting",c:"Credential Access",s:"High",p:"\\bpassword\\b.*\\bget\\b|\\bget\\b.*\\bpassword\\b",d:"Password-related variable or command.",r:"Review context for harvesting.",m:["T1555"]},
{id:"PSA-117",n:"Browser History Access",c:"Credential Access",s:"High",p:"\\bAppData\\\\Local\\\\Google\\\\Chrome\\\\User Data\\b",d:"Chrome profile path targeted.",r:"Credential or history theft indicator.",m:["T1555.001"]},
{id:"PSA-118",n:"Firefox Profile Access",c:"Credential Access",s:"High",p:"\\bAppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\b",d:"Firefox profile path targeted.",r:"Credential or history theft indicator.",m:["T1555.001"]},
{id:"PSA-119",n:"Handle.exe Reference",c:"Credential Access",s:"Medium",p:"\\bhandle\\.exe\\b",d:"Sysinternals Handle utility.",r:"Can be used to find LSASS handles.",m:["T1003.001"]},
{id:"PSA-120",n:"Get-Process LSASS",c:"Credential Access",s:"Critical",p:"\\bGet-Process\\b.*\\blsass\\b",d:"LSASS process targeting.",r:"Precedes memory dumping.",m:["T1003.001"]},
{id:"PSA-121",n:"Rubeus Reference",c:"Credential Access",s:"Critical",p:"\\bRubeus\\b",d:"Rubeus Kerberos abuse tool.",r:"Definitive credential/kerberos abuse indicator.",m:["T1558"]},
{id:"PSA-122",n:"Kerberoasting",c:"Credential Access",s:"High",p:"\\bRequest-MitKerberosTicket\\b|\\bInvoke-Kerberoast\\b",d:"Kerberoasting activity.",r:"Credential theft indicator.",m:["T1558.003"]},
{id:"PSA-123",n:"AS-REP Roasting",c:"Credential Access",s:"High",p:"\\bInvoke-ASREPRoast\\b",d:"AS-REP Roasting activity.",r:"Credential theft indicator.",m:["T1558.004"]},
{id:"PSA-124",n:"Vault Credential Access",c:"Credential Access",s:"High",p:"\\bWindows\\.Security\\.Credentials\\b",d:"Windows Credential Vault API.",r:"Credential harvesting indicator.",m:["T1555"]},
{id:"PSA-125",n:"Unattend.xml Access",c:"Credential Access",s:"High",p:"\\bunattend\\.xml\\b",d:"Unattended installation file.",r:"Often contains plaintext credentials.",m:["T1552.001"]},

// --- PERSISTENCE (126-155) ---
{id:"PSA-126",n:"Scheduled Task Creation",c:"Persistence",s:"High",p:"\\bNew-ScheduledTask\\b|\\bschtasks\\s+/create\\b",d:"Scheduled task creation.",r:"Verify the task action and trigger.",m:["T1053.005"]},
{id:"PSA-127",n:"Register-ScheduledJob",c:"Persistence",s:"High",p:"\\bRegister-ScheduledJob\\b",d:"PowerShell scheduled job creation.",r:"Verify the job script block.",m:["T1053.005"]},
{id:"PSA-128",n:"Registry Run Key",c:"Persistence",s:"High",p:"\\\\CurrentVersion\\\\Run\\b",d:"Registry Run key modification.",r:"Classic persistence mechanism.",m:["T1547.001"]},
{id:"PSA-129",n:"Registry RunOnce Key",c:"Persistence",s:"High",p:"\\\\CurrentVersion\\\\RunOnce\\b",d:"Registry RunOnce key modification.",r:"Persistence mechanism.",m:["T1547.001"]},
{id:"PSA-130",n:"Startup Folder",c:"Persistence",s:"Medium",p:"\\\\Startup\\b",d:"Startup folder reference.",r:"Check for dropped executables or scripts.",m:["T1547.001"]},
{id:"PSA-131",n:"Service Creation",c:"Persistence",s:"High",p:"\\bNew-Service\\b",d:"Windows service creation.",r:"Verify the service binary path.",m:["T1543.003"]},
{id:"PSA-132",n:"WMI Event Subscription",c:"Persistence",s:"Critical",p:"\\b__EventFilter\\b|\\b__FilterToConsumerBinding\\b|\\b__EventConsumer\\b",d:"WMI event subscription.",r:"Advanced persistence mechanism.",m:["T1546.003"]},
{id:"PSA-133",n:"PowerShell Profile",c:"Persistence",s:"Medium",p:"\\$PROFILE|\\\\WindowsPowerShell\\\\profile\\.ps1\\b",d:"PowerShell profile modification.",r:"Check for added malicious commands.",m:["T1546.013"]},
{id:"PSA-134",n:"Login Script",c:"Persistence",s:"Medium",p:"\\\\Netlogon\\\\|\\\\logon\\.bat\\b",d:"Login script reference.",r:"Domain-wide persistence indicator.",m:["T1037"]},
{id:"PSA-135",n:"Group Policy Object",c:"Persistence",s:"High",p:"\\bGroupPolicy\\b|\\bGPO\\b",d:"GPO manipulation.",r:"Domain-wide persistence indicator.",m:["T1484"]},
{id:"PSA-136",n:"Image File Execution Options",c:"Persistence",s:"Critical",p:"\\\\Image File Execution Options\\b",d:"IFEO debugger hijack.",r:"Advanced persistence/evasion.",m:["T1546.012"]},
{id:"PSA-137",n:"AppInit_DLLs",c:"Persistence",s:"Critical",p:"\\\\AppInit_DLLs\\b",d:"AppInit_DLLs registry key.",r:"DLL load persistence mechanism.",m:["T1546.010"]},
{id:"PSA-138",n:"Winlogon Helper",c:"Persistence",s:"Critical",p:"\\\\Winlogon\\\\Shell\\b|\\\\Winlogon\\\\Userinit\\b",d:"Winlogon registry modification.",r:"Advanced persistence mechanism.",m:["T1547.004"]},
{id:"PSA-139",n:"BITS Job Persistence",c:"Persistence",s:"High",p:"\\bStart-BitsTransfer\\b",d:"BITS job creation.",r:"Can be used for persistent download.",m:["T1197"]},
{id:"PSA-140",n:"Registry Service Key",c:"Persistence",s:"High",p:"\\\\Services\\\\[\\w]+\\\\ImagePath\\b",d:"Service ImagePath modification.",r:"Persistence or privilege escalation.",m:["T1543.003"]},
{id:"PSA-141",n:"Tearmsrv.dll Modification",c:"Persistence",s:"Critical",p:"\\btermsrv\\.dll\\b",d:"Terminal services DLL targeted.",r:"RDP persistence indicator.",m:["T1556"]},
{id:"PSA-142",n:"COM Hijacking",c:"Persistence",s:"High",p:"\\\\InprocServer32\\b",d:"COM InprocServer32 modification.",r:"COM hijacking persistence.",m:["T1546.015"]},
{id:"PSA-143",n:"Silent Process Exit",c:"Persistence",s:"High",p:"\\\\SilentProcessExit\\b",d:"Silent Process Exit registry key.",r:"Persistence mechanism.",m:["T1546.012"]},
{id:"PSA-144",n:"Time Provider",c:"Persistence",s:"High",p:"\\\\TimeProviders\\b",d:"Time provider registry key.",r:"Persistence mechanism.",m:["T1547.003"]},
{id:"PSA-145",n:"LSA Provider",c:"Persistence",s:"Critical",p:"\\\\LSA\\\\Security Packages\\b",d:"LSA security package addition.",r:"Advanced persistence/credential theft.",m:["T1556.001"]},
{id:"PSA-146",n:"StartupApproved",c:"Persistence",s:"Medium",p:"\\\\StartupApproved\\b",d:"StartupApproved registry key.",r:"Persistence mechanism.",m:["T1547.001"]},
{id:"PSA-147",n:"Explorer Run",c:"Persistence",s:"High",p:"\\\\Explorer\\\\Run\\b",d:"Explorer Run key.",r:"Persistence mechanism.",m:["T1547.001"]},
{id:"PSA-148",n:"MountPoints2",c:"Persistence",s:"Medium",p:"\\\\MountPoints2\\b",d:"MountPoints2 registry key.",r:"USB-based persistence.",m:["T1547.001"]},
{id:"PSA-149",n:"Telephony",c:"Persistence",s:"Medium",p:"\\\\Telephony\\b",d:"Telephony registry key.",r:"Persistence mechanism.",m:["T1547.001"]},
{id:"PSA-150",n:"Open Command",c:"Persistence",s:"Medium",p:"\\\\shell\\\\open\\\\command\\b",d:"File association hijack.",r:"Persistence mechanism.",m:["T1546.001"]},

// --- DISCOVERY (151-175) ---
{id:"PSA-151",n:"Get-Process",c:"Discovery",s:"Low",p:"\\bGet-Process\\b|\\bgps\\b",d:"Process enumeration.",r:"Common administrative task, but also discovery.",m:["T1057"]},
{id:"PSA-152",n:"Get-Service",c:"Discovery",s:"Low",p:"\\bGet-Service\\b|\\bgsv\\b",d:"Service enumeration.",r:"Discovery indicator.",m:["T1007"]},
{id:"PSA-153",n:"Get-ComputerInfo",c:"Discovery",s:"Low",p:"\\bGet-ComputerInfo\\b",d:"System information gathering.",r:"Reconnaissance indicator.",m:["T1082"]},
{id:"PSA-154",n:"Get-WmiObject",c:"Discovery",s:"Medium",p:"\\bGet-WmiObject\\b",d:"WMI query execution.",r:"Check the WMI class being queried.",m:["T1047"]},
{id:"PSA-155",n:"Get-CimInstance",c:"Discovery",s:"Medium",p:"\\bGet-CimInstance\\b",d:"CIM query execution.",r:"Check the CIM class being queried.",m:["T1047"]},
{id:"PSA-156",n:"Get-NetAdapter",c:"Discovery",s:"Low",p:"\\bGet-NetAdapter\\b",d:"Network adapter enumeration.",r:"Network discovery.",m:["T1016"]},
{id:"PSA-157",n:"Get-NetIPAddress",c:"Discovery",s:"Low",p:"\\bGet-NetIPAddress\\b",d:"IP address enumeration.",r:"Network discovery.",m:["T1016"]},
{id:"PSA-158",n:"Get-LocalUser",c:"Discovery",s:"Medium",p:"\\bGet-LocalUser\\b",d:"Local user enumeration.",r:"Discovery indicator.",m:["T1087.001"]},
{id:"PSA-159",n:"Get-LocalGroup",c:"Discovery",s:"Medium",p:"\\bGet-LocalGroup\\b",d:"Local group enumeration.",r:"Discovery indicator.",m:["T1069.001"]},
{id:"PSA-160",n:"Get-ADUser",c:"Discovery",s:"Medium",p:"\\bGet-ADUser\\b",d:"Active Directory user enumeration.",r:"Domain discovery indicator.",m:["T1087.002"]},
{id:"PSA-161",n:"Get-ADComputer",c:"Discovery",s:"Medium",p:"\\bGet-ADComputer\\b",d:"Active Directory computer enumeration.",r:"Domain discovery indicator.",m:["T1018"]},
{id:"PSA-162",n:"NLTest",c:"Discovery",s:"Medium",p:"\\bnltest\\b",d:"Domain trust and controller discovery.",r:"Domain discovery indicator.",m:["T1482"]},
{id:"PSA-163",n:"Net Config",c:"Discovery",s:"Low",p:"\\bnet\\s+config\\b",d:"Network configuration display.",r:"Discovery indicator.",m:["T1016"]},
{id:"PSA-164",n:"QUser",c:"Discovery",s:"Low",p:"\\bquser\\b",d:"Logged-on user discovery.",r:"Discovery indicator.",m:["T1033"]},
{id:"PSA-165",n:"Query Session",c:"Discovery",s:"Low",p:"\\bquery\\s+session\\b",d:"Session discovery.",r:"Discovery indicator.",m:["T1033"]},
{id:"PSA-166",n:"Tasklist",c:"Discovery",s:"Low",p:"\\btasklist\\b",d:"Running task enumeration.",r:"Discovery indicator.",m:["T1057"]},
{id:"PSA-167",n:"Get-NetFirewallRule",c:"Discovery",s:"Medium",p:"\\bGet-NetFirewallRule\\b",d:"Firewall rule enumeration.",r:"Defense evasion preparation.",m:["T1518.001"]},
{id:"PSA-168",n:"Get-NetTCPConnection",c:"Discovery",s:"Low",p:"\\bGet-NetTCPConnection\\b",d:"Active TCP connection enumeration.",r:"Network discovery.",m:["T1049"]},
{id:"PSA-169",n:"System Drive Enumeration",c:"Discovery",s:"Low",p:"\\bGet-PSDrive\\b",d:"Drive enumeration.",r:"File discovery indicator.",m:["T1083"]},
{id:"PSA-170",n:"Get-ChildItem Recursive",c:"Discovery",s:"Low",p:"\\bGet-ChildItem\\s+-Recurse\\b",d:"Recursive file enumeration.",r:"File discovery indicator.",m:["T1083"]},
{id:"PSA-171",n:"Select-String Password",c:"Discovery",s:"High",p:"\\bSelect-String\\b.*\\bpassword\\b",d:"Searching files for passwords.",r:"Credential discovery indicator.",m:["T1552"]},
{id:"PSA-172",n:"Get-Content on SAM",c:"Credential Access",s:"Critical",p:"\\bGet-Content\\b.*\\\\SAM\\b",d:"Attempt to read SAM file.",r:"Credential theft indicator.",m:["T1003.002"]},
{id:"PSA-173",n:"Environment Variable Dump",c:"Discovery",s:"Low",p:"\\bGet-ChildItem\\s+Env:\\b",d:"Environment variable enumeration.",r:"May reveal credentials or paths.",m:["T1082"]},
{id:"PSA-174",n:"Get-Clipboard",c:"Collection",s:"Medium",p:"\\bGet-Clipboard\\b",d:"Clipboard content access.",r:"Data collection indicator.",m:["T1115"]},
{id:"PSA-175",n:"Screen Capture",c:"Collection",s:"High",p:"\\bAdd-Type.*Windows\\.Forms.*Screen\\b",d:"Screen capture attempt.",r:"Data collection indicator.",m:["T1113"]},

// --- PRIVILEGE ESCALATION (176-190) ---
{id:"PSA-176",n:"UAC Bypass Indicator",c:"Privilege Escalation",s:"Critical",p:"\\bFodHelper\\b|\\bSdclt\\b",d:"Known UAC bypass target.",r:"Privilege escalation indicator.",m:["T1548.002"]},
{id:"PSA-177",n:"COM Hijack UAC",c:"Privilege Escalation",s:"Critical",p:"\\bmscfile\\b|\\bms-settings\\b",d:"UAC bypass via COM hijacking.",r:"Privilege escalation indicator.",m:["T1548.002"]},
{id:"PSA-178",n:"Unquoted Service Path",c:"Privilege Escalation",s:"High",p:"\\bGet-CimInstance.*Win32_Service.*PathName\\b",d:"Checking for unquoted service paths.",r:"Privilege escalation reconnaissance.",m:["T1574.009"]},
{id:"PSA-179",n:"AlwaysInstallElevated",c:"Privilege Escalation",s:"High",p:"\\bAlwaysInstallElevated\\b",d:"MSI always install elevated check.",r:"Privilege escalation indicator.",m:["T1548.002"]},
{id:"PSA-180",n:"SeImpersonatePrivilege",c:"Privilege Escalation",s:"High",p:"\\bSeImpersonatePrivilege\\b",d:"Impersonation privilege check.",r:"Precedes Potato exploits.",m:["T1548.002"]},
{id:"PSA-181",n:"SeAssignPrimaryToken",c:"Privilege Escalation",s:"High",p:"\\bSeAssignPrimaryTokenPrivilege\\b",d:"Primary token assignment privilege.",r:"Precedes Potato exploits.",m:["T1548.002"]},
{id:"PSA-182",n:"Potato Exploit Reference",c:"Privilege Escalation",s:"Critical",p:"\\bJuicyPotato\\b|\\bRoguePotato\\b|\\bPrintSpoofer\\b",d:"Known privilege escalation exploit.",r:"Definitive privilege escalation indicator.",m:["T1548.002"]},
{id:"PSA-183",n:"Token Privilege Adjustment",c:"Privilege Escalation",s:"High",p:"\\bAdjustTokenPrivileges\\b",d:"Token privilege modification.",r:"Privilege escalation indicator.",m:["T1548.002"]},
{id:"PSA-184",n:"DLL Hijacking",c:"Privilege Escalation",s:"High",p:"\\bSetDllDirectory\\b",d:"DLL search order manipulation.",r:"Privilege escalation or persistence.",m:["T1574.001"]},
{id:"PSA-185",n:"Kernel Exploit Reference",c:"Privilege Escalation",s:"Critical",p:"\\bCVE-20\\d{2}-\\d{4,5}\\b",d:"Specific CVE reference.",r:"Check if exploit code is present.",m:["T1068"]},
{id:"PSA-186",n:"Registry ACL Modification",c:"Privilege Escalation",s:"High",p:"\\bSet-Acl\\b.*\\\\Registry\\b",d:"Registry ACL modification.",r:"Privilege escalation indicator.",m:["T1548.002"]},
{id:"PSA-187",n:"Service Permission Modification",c:"Privilege Escalation",s:"High",p:"\\bsc\\\\s+sdset\\b",d:"Service security descriptor modification.",r:"Privilege escalation indicator.",m:["T1548.002"]},
{id:"PSA-188",n:"Scheduled Task Privilege",c:"Privilege Escalation",s:"High",p:"\\b-Highest\\b",d:"Scheduled task highest privilege flag.",r:"Privilege escalation indicator.",m:["T1548.002"]},
{id:"PSA-189",n:"Runas Command",c:"Privilege Escalation",s:"Medium",p:"\\brunas\\b",d:"Runas command execution.",r:"Check for credential prompting or bypass.",m:["T1548.002"]},
{id:"PSA-190",n:"Start-Process Elevated",c:"Privilege Escalation",s:"Medium",p:"\\bStart-Process\\s+-Verb\\s+RunAs\\b",d:"Elevated process execution request.",r:"UAC prompt trigger.",m:["T1548.002"]},

// --- LATERAL MOVEMENT (191-205) ---
{id:"PSA-191",n:"WinRM Enable",c:"Lateral Movement",s:"High",p:"\\bEnable-PSRemoting\\b",d:"WinRM service enablement.",r:"Prepares system for remote access.",m:["T1021.006"]},
{id:"PSA-192",n:"PSExec Reference",c:"Lateral Movement",s:"High",p:"\\bPsExec\\b",d:"Sysinternals PsExec utility.",r:"Lateral movement indicator.",m:["T1569.002"]},
{id:"PSA-193",n:"WMI Remote Execution",c:"Lateral Movement",s:"High",p:"\\bWin32_Process\\b.*\\\\\\b",d:"Remote WMI process creation.",r:"Lateral movement indicator.",m:["T1047"]},
{id:"PSA-194",n:"SMB Admin Share",c:"Lateral Movement",s:"High",p:"\\\\[\\w-]+\\\\[cC|ADMIN\\$]\\b",d:"Administrative SMB share access.",r:"Lateral movement indicator.",m:["T1021.002"]},
{id:"PSA-195",n:"Remote Registry",c:"Lateral Movement",s:"High",p:"\\\\RemoteRegistry\\b",d:"Remote registry service interaction.",r:"Lateral movement indicator.",m:["T1021.002"]},
{id:"PSA-196",n:"RDP Enable",c:"Lateral Movement",s:"High",p:"\\bEnable-TSRemoting\\b|\\bSet-ItemProperty.*fDenyTSConnections.*0\\b",d:"Remote Desktop enablement.",r:"Prepares system for remote access.",m:["T1021.001"]},
{id:"PSA-197",n:"MSTSC Execution",c:"Lateral Movement",s:"Medium",p:"\\bmstsc\\b",d:"Remote Desktop client execution.",r:"Lateral movement indicator.",m:["T1021.001"]},
{id:"PSA-198",n:"SSH Execution",c:"Lateral Movement",s:"Medium",p:"\\bssh\\b",d:"SSH client execution.",r:"Lateral movement indicator.",m:["T1021.004"]},
{id:"PSA-199",n:"Pass-the-Hash Reference",c:"Lateral Movement",s:"Critical",p:"\\bpth\\b|\\bpass\\s+the\\s+hash\\b",d:"Pass-the-hash technique reference.",r:"Lateral movement indicator.",m:["T1550.002"]},
{id:"PSA-200",n:"Invoke-WmiMethod",c:"Lateral Movement",s:"High",p:"\\bInvoke-WmiMethod\\b",d:"WMI method invocation.",r:"Check for remote execution.",m:["T1047"]},
{id:"PSA-201",n:"Invoke-CimMethod",c:"Lateral Movement",s:"High",p:"\\bInvoke-CimMethod\\b",d:"CIM method invocation.",r:"Check for remote execution.",m:["T1047"]},
{id:"PSA-202",n:"Enter-PSSession",c:"Lateral Movement",s:"Medium",p:"\\bEnter-PSSession\\b",d:"Interactive PowerShell remoting.",r:"Lateral movement indicator.",m:["T1021.006"]},
{id:"PSA-203",n:"New-PSSession",c:"Lateral Movement",s:"Medium",p:"\\bNew-PSSession\\b",d:"PowerShell session creation.",r:"Lateral movement indicator.",m:["T1021.006"]},
{id:"PSA-204",n:"Copy-Item to Remote",c:"Lateral Movement",s:"Medium",p:"\\bCopy-Item\\s+-ToSession\\b",d:"File copy to remote session.",r:"Lateral movement indicator.",m:["T1021.006"]},
{id:"PSA-205",n:"Net Use Command",c:"Lateral Movement",s:"Medium",p:"\\bnet\\s+use\\b",d:"Network share connection.",r:"Lateral movement indicator.",m:["T1021.002"]},

// --- PROCESS INJECTION (206-215) ---
{id:"PSA-206",n:"VirtualAllocEx",c:"Process Injection",s:"Critical",p:"\\bVirtualAllocEx\\b",d:"Remote memory allocation.",r:"Strong process injection indicator.",m:["T1055"]},
{id:"PSA-207",n:"WriteProcessMemory",c:"Process Injection",s:"Critical",p:"\\bWriteProcessMemory\\b",d:"Remote process memory write.",r:"Strong process injection indicator.",m:["T1055"]},
{id:"PSA-208",n:"CreateRemoteThread",c:"Process Injection",s:"Critical",p:"\\bCreateRemoteThread\\b",d:"Remote thread creation.",r:"Strong process injection indicator.",m:["T1055"]},
{id:"PSA-209",n:"OpenProcess",c:"Process Injection",s:"High",p:"\\bOpenProcess\\b",d:"Process handle acquisition.",r:"Precedes process injection.",m:["T1055"]},
{id:"PSA-210",n:"NtWriteVirtualMemory",c:"Process Injection",s:"Critical",p:"\\bNtWriteVirtualMemory\\b",d:"Native API memory write.",r:"Strong process injection indicator.",m:["T1055"]},
{id:"PSA-211",n:"QueueUserAPC",c:"Process Injection",s:"Critical",p:"\\bQueueUserAPC\\b",d:"APC injection technique.",r:"Strong process injection indicator.",m:["T1055.004"]},
{id:"PSA-212",n:"SetWindowsHookEx",c:"Process Injection",s:"High",p:"\\bSetWindowsHookEx\\b",d:"Windows hook injection.",r:"Process injection indicator.",m:["T1055.003"]},
{id:"PSA-213",n:"Reflective Loading",c:"Process Injection",s:"Critical",p:"\\bReflectiveLoader\\b|\\bInvoke-ReflectivePEInjection\\b",d:"Reflective DLL injection.",r:"Strong process injection indicator.",m:["T1055.001"]},
{id:"PSA-214",n:"Shellcode Execution",c:"Process Injection",s:"Critical",p:"\\bshellcode\\b",d:"Shellcode reference.",r:"Strong process injection indicator.",m:["T1055"]},
{id:"PSA-215",n:"Inline Assembly",c:"Process Injection",s:"Critical",p:"\\basm\\b",d:"Inline assembly detected.",r:"Highly suspicious in PowerShell.",m:["T1055"]},

// --- RANSOMWARE (216-230) ---
{id:"PSA-216",n:"Shadow Copy Deletion",c:"Impact",s:"Critical",p:"\\bvssadmin\\s+delete\\s+shadows\\b|\\bDeleteVolumeShadowCopy\\b",d:"Volume shadow copy deletion.",r:"Strong ransomware indicator.",m:["T1490"]},
{id:"PSA-217",n:"WBAdmin Delete",c:"Impact",s:"Critical",p:"\\bwbadmin\\s+delete\\b",d:"Windows backup deletion.",r:"Strong ransomware indicator.",m:["T1490"]},
{id:"PSA-218",n:"BCDedit Recovery Disable",c:"Impact",s:"Critical",p:"\\bbcdedit\\s+/set\\s+\\{default\\}\\s+recoveryenabled\\s+no\\b",d:"Boot recovery disabled.",r:"Strong ransomware indicator.",m:["T1490"]},
{id:"PSA-219",n:"Mass File Extension Change",c:"Impact",s:"Critical",p:"\\bRename-Item\\b.*\\b\\.(locked|crypto|encrypted)\\b",d:"Mass file renaming.",r:"Ransomware encryption indicator.",m:["T1486"]},
{id:"PSA-220",n:"Ransom Note Creation",c:"Impact",s:"Critical",p:"\\bREADME\\.txt\\b|\\bHOW_TO_DECRYPT\\b",d:"Ransom note file creation.",r:"Ransomware indicator.",m:["T1486"]},
{id:"PSA-221",n:"Bitcoin Address",c:"Impact",s:"High",p:"\\b(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}\\b",d:"Cryptocurrency address detected.",r:"Ransomware payment indicator.",m:["T1486"]},
{id:"PSA-222",n:"Tor Reference",c:"Impact",s:"High",p:"\\b\\.onion\\b",d:"Tor network reference.",r:"Ransomware C2 or payment indicator.",m:["T1486"]},
{id:"PSA-223",n:"Stop Service",c:"Impact",s:"Medium",p:"\\bStop-Service\\b",d:"Service termination.",r:"Check if critical services are targeted.",m:["T1489"]},
{id:"PSA-224",n:"Kill Process",c:"Impact",s:"Medium",p:"\\bStop-Process\\b|\\btaskkill\\b",d:"Process termination.",r:"Check if security or database processes are targeted.",m:["T1489"]},
{id:"PSA-225",n:"Clear Disk",c:"Impact",s:"Critical",p:"\\bClear-Disk\\b",d:"Disk clearing command.",r:"Destructive behavior.",m:["T1485"]},
{id:"PSA-226",n:"Format Volume",c:"Impact",s:"Critical",p:"\\bFormat-Volume\\b",d:"Volume formatting command.",r:"Destructive behavior.",m:["T1485"]},
{id:"PSA-227",n:"Remove-Item Recursive",c:"Impact",s:"High",p:"\\bRemove-Item\\s+-Recurse\\s+-Force\\b",d:"Forceful recursive deletion.",r:"Destructive behavior.",m:["T1485"]},
{id:"PSA-228",n:"Cipher Wipe",c:"Impact",s:"Critical",p:"\\bcipher\\s+/w\\b",d:"Disk wiping command.",r:"Destructive behavior.",m:["T1485"]},
{id:"PSA-229",n:"SDelete Reference",c:"Impact",s:"Critical",p:"\\bsdelete\\b",d:"Sysinternals secure delete utility.",r:"Destructive behavior.",m:["T1485"]},
{id:"PSA-230",n:"Wevtutil Clear All",c:"Impact",s:"High",p:"\\bwevtutil\\s+el\\s*\\|\\s*wevtutil\\s+cl\\b",d:"Mass event log clearing.",r:"Anti-forensics behavior.",m:["T1070.001"]},

// --- COLLECTION & EXFILTRATION (231-250) ---
{id:"PSA-231",n:"Compress-Archive",c:"Collection",s:"Medium",p:"\\bCompress-Archive\\b",d:"File archiving.",r:"Check what is being archived.",m:["T1560.001"]},
{id:"PSA-232",n:"Zip File Creation",c:"Collection",s:"Medium",p:"\\b\\.zip\\b",d:"ZIP file reference.",r:"Check for data staging.",m:["T1560.001"]},
{id:"PSA-233",n:"Tar File Creation",c:"Collection",s:"Medium",p:"\\b\\.tar\\b",d:"TAR file reference.",r:"Check for data staging.",m:["T1560.001"]},
{id:"PSA-234",n:"HTTP POST Request",c:"Exfiltration",s:"High",p:"\\bMethod\\s*=\\s*['\"]POST['\"]\\b",d:"HTTP POST method detected.",r:"Potential data exfiltration.",m:["T1048.001"]},
{id:"PSA-235",n:"FTP Put",c:"Exfiltration",s:"High",p:"\\bftp\\s+-s\\b",d:"FTP script execution.",r:"Potential data exfiltration.",m:["T1048.002"]},
{id:"PSA-236",n:"Cloud Storage Reference",c:"Exfiltration",s:"Medium",p:"\\bonedrive\\b|\\bdropbox\\b|\\bgoogle\\s+drive\\b",d:"Cloud storage reference.",r:"Check for unauthorized data sync.",m:["T1567"]},
{id:"PSA-237",n:"Mail Message",c:"Exfiltration",s:"Medium",p:"\\bSend-MailMessage\\b",d:"Email sending command.",r:"Check for sensitive data in attachments.",m:["T1048.003"]},
{id:"PSA-238",n:"Out-File to Network",c:"Exfiltration",s:"High",p:"\\bOut-File\\s+-FilePath\\s+\\\\\\\\",d:"File output to network share.",r:"Potential data staging or exfiltration.",m:["T1048.002"]},
{id:"PSA-239",n:"Set-Clipboard",c:"Collection",s:"Medium",p:"\\bSet-Clipboard\\b",d:"Clipboard modification.",r:"Check for data manipulation.",m:["T1115"]},
{id:"PSA-240",n:"Keylogging Reference",c:"Collection",s:"Critical",p:"\\bGetAsyncKeyState\\b|\\bkeylog\\b",d:"Keylogging API or reference.",r:"Definitive collection indicator.",m:["T1056.001"]},
{id:"PSA-241",n:"Microphone Access",c:"Collection",s:"High",p:"\\bAudio\\b.*\\bCapture\\b",d:"Audio capture attempt.",r:"Collection indicator.",m:["T1123"]},
{id:"PSA-242",n:"Webcam Access",c:"Collection",s:"High",p:"\\bWebCam\\b|\\bVideo\\s+Capture\\b",d:"Webcam access attempt.",r:"Collection indicator.",m:["T1125"]},
{id:"PSA-243",n:"Document Discovery",c:"Collection",s:"Medium",p:"\\b\\*\\.docx\\b|\\b\\*\\.xlsx\\b|\\b\\*\\.pdf\\b",d:"Document file search.",r:"Data collection indicator.",m:["T1213"]},
{id:"PSA-244",n:"Database Discovery",c:"Collection",s:"Medium",p:"\\b\\*\\.mdf\\b|\\b\\*\\.sql\\b|\\b\\*\\.db\\b",d:"Database file search.",r:"Data collection indicator.",m:["T1213"]},
{id:"PSA-245",n:"SSH Key Discovery",c:"Collection",s:"High",p:"\\b\\\\\\.ssh\\\\\\b",d:"SSH directory access.",r:"Credential collection indicator.",m:["T1552.004"]},
{id:"PSA-246",n:"AWS Credentials",c:"Collection",s:"Critical",p:"\\b\\\\\\.aws\\\\credentials\\b",d:"AWS credentials file access.",r:"Cloud credential theft indicator.",m:["T1552.005"]},
{id:"PSA-247",n:"GCP Credentials",c:"Collection",s:"Critical",p:"\\bapplication_default_credentials\\.json\\b",d:"GCP credentials file access.",r:"Cloud credential theft indicator.",m:["T1552.005"]},
{id:"PSA-248",n:"Kubeconfig Access",c:"Collection",s:"Critical",p:"\\b\\\\\\.kube\\\\config\\b",d:"Kubernetes config access.",r:"Cloud credential theft indicator.",m:["T1552.005"]},
{id:"PSA-249",n:"Exfiltration Domain",c:"Exfiltration",s:"High",p:"\\bexfil\\b|\\bupload\\b|\\btransfer\\b",d:"Exfiltration-related keywords.",r:"Review context for data transfer.",m:["T1048"]},
{id:"PSA-250",n:"DNS Exfiltration",c:"Exfiltration",s:"High",p:"\\bResolve-DnsName\\b.*\\b\\$\\b",d:"Dynamic DNS query.",r:"Potential DNS tunneling exfiltration.",m:["T1048.003"]}
];